### ISSUE TITLE
Loopback 4 support?

### ISSUE THREAD

**Issue by 128keaton** [strongloop/loopback-soap#26]
# Description/Steps to reproduce

1. Install the legacy Loopback CLI package: `npm i -g loopback-cli`
2. Create a new Loopback 4 application: `lb4 test-soap`
3. Try to use the `lb soap` command: `cd test-soap && lb-soap`

# Link to reproduction sandbox
Not really needed...

# Expected result
Generation of data sources, models, and services.

# Additional information
Output: 
```bash
$ lb soap my.soap.endpoint/blah\?WSDL
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Invalid workspace: no facets found.
    at C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-workspace\common\models\workspace.js:478:14
    at C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-datasource-juggler\lib\dao.js:1719:9
    at C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1140:9
    at C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:473:16
    at eachOfArrayLike (C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1057:9)
    at eachOf (C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1117:5)
    at _asyncMap (C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1133:5)
    at Object.map (C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1122:16)
    at allCb (C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-datasource-juggler\lib\dao.js:1630:13)
    at C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\loopback-datasource-juggler\lib\connectors\memory.js:512:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\keaton\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Node:
 `win32 x64 10.16.0`

npm: 
```bash
+-- @loopback/boot@1.5.0
+-- @loopback/context@1.21.1
+-- @loopback/core@1.9.0
+-- @loopback/openapi-v3@1.9.1
+-- @loopback/repository@1.10.1
+-- @loopback/rest@1.16.6
+-- @loopback/rest-explorer@1.3.1
+-- @loopback/service-proxy@1.3.0
+-- loopback-cache@0.2.2
+-- loopback-connector-soap@5.0.0
```

**Comment by raymondfeng** [comment]
We haven't ported `lb soap` to LoopBack 4 yet. Maybe you should try `lb4 service` to access a SOAP WS from LB4.

**Comment by 128keaton** [comment]
@raymondfeng 

Right, which is why I opened the issue. I am already using `lb4 service`, but that isn't the point of `lb soap`, which is model generation/definition.

**Comment by dhmlau** [comment]
@raymondfeng, would we intend to have `lb soap` equivalent capabilities in LB4? or `lb4 service` is meant to replace that? Thanks.

**Comment by dhmlau** [comment]
The current workaround is to use `lb4 service`. For equivalent functionality as `lb soap`, please continue the discussion over https://github.com/strongloop/loopback-next/issues/5282. With that, I'd like to close this issue. Thanks.
